### ISSUE TITLE
Allocation of arrays on the stack

### ISSUE THREAD

**Issue by hroest** [Roestlab/DIAlignR#11]
There is an issue with allocation of large arrays on the stack introduced in 72e3877b2675db4840454db82ac2a99525 :  
https://github.com/Roestlab/DIAlignR/blob/eaef095f4db01fa6e42f8037eec812b3afbbbd17/src/affinealignment.cpp#L43-L48

the issue is that you should not allocate large arrays on the stack, see https://stackoverflow.com/questions/32322915/why-does-this-array-allocation-cause-a-segfault and these arrays could become pretty large for long chromatograms (several hundred datapoints). We should allocate them on the heap.

**Comment by shubham1637** [comment]
Got it. I do not need this code anymore. Previously, I was thinking of using the max score/ cumulative score for confidence calculation. However, I want to keep the code for future (just-in-case). Can I comment out the lines? or should I remove all the unused code?

**Comment by hroest** [comment]
> Got it. I do not need this code anymore. Previously, I was thinking of using the max score/ cumulative score for confidence calculation. However, I want to keep the code for future (just-in-case). Can I comment out the lines? or should I remove all the unused code?

i suggest to remove the code. You can always go back to this version of git if you need the code again. Or even better, create a branch at this point with a tag indicating it contains the code so that you find it again.

**Comment by hroest** [comment]
I suggest to delete it, there is a significant performance impact:

```
python -m timeit  -r 3 -s "import DIAlignPy; import test_data as d; d.c(128); obj = DIAlignPy.AffineAlignObj(3300,3300);" 'DIAlignPy.alignChromatogramsCppSimple(obj, d.chromatograms, d.chromatograms2,b"none", d.rt_data, d.rt_data2, b"mean", b"cosineAngle")'
10 loops, best of 3: 78.3 msec per loop
```

after removing it, it is 11% faster

```
python -m timeit  -r 3 -s "import DIAlignPy; import test_data as d; d.c(128); obj = DIAlignPy.AffineAlignObj(3300,3300);" 'DIAlignPy.alignChromatogramsCppSimple(obj, d.chromatograms, d.chromatograms2,b"none", d.rt_data, d.rt_data2, b"mean", b"cosineAngle")'
10 loops, best of 3: 70 msec per loop
```

**Comment by shubham1637** [comment]
Removed this code and created a new pull request.
