### ISSUE TITLE
Error when run the example of areaIntegrator

### ISSUE THREAD

**Issue by zhengfj1994** [Roestlab/DIAlignR#36]
Hi:

When I run the example of areaIntegrator:

data("XIC_QFNNTDIVLLEDFQK_3_DIAlignR", package = "DIAlignR")
XICs <- XIC_QFNNTDIVLLEDFQK_3_DIAlignR[["hroest_K120809_Strep0%PlasmaBiolRepl2_R04_SW_filt"]][["4618"]]
l1 <- lapply(XICs, `[[`, 1)
l2 <- lapply(XICs, `[[`, 2)
areaIntegrator(l1, l2, left = 5203.7, right = 5268.5, "intensity_sum", "base_to_base", FALSE, TRUE)

l1 and l2 is empty.

And the parameter named baseSubtraction is not in use.

Best wishes

**Comment by shubham1637** [comment]
The package is built on bioconductor and all the examples and test-cases are run. Hence, it must be working.
You might have forgot to call the package `library(DIAlignR)`.
