### ISSUE TITLE
DIAlignR Metabolomics

### ISSUE THREAD

**Issue by bruadi** [Roestlab/DIAlignR#39]
Hi, 
I wanted to use DIAlignR for metabolomics (SWATH). I installed everything necessary for it from this website https://htmlpreview.github.io/?https://github.com/shubham1637/DIAlignR/master/vignettes/DIAlignR-vignette.html. 
I converted the XICs and put them as *.chrom.mzML in the datapath "dataPath <- system.file("metabo", package = "DIAlignR") in the xics folder. 
I renamed the scored_ms1ms2.osw file from Pyprophet to merged.osw and also put it in the osw folder. 
I get this error message every time: 

"The names in the RUN table of the osw files do not match the mzML file names.
Check if you have the correct file names.
Error in getRunNames(dataPath, oswMerged, params) : 
  Name mismatch between osw and mzML files.
> For all analytes in all runs, keep them as NULL.
> alignTargetedRuns(dataPath = dataPath, outFile = "test.csv", runs = NULL, oswMerged = TRUE, params = params)
The file merged.osw is searched.
40 runs are in the file merged.osw
0 .chrom.sqMass files were found.
The following files have no counterpart in the xics directory.
 [1] "18625_PS-B1-25" "18625_PS-B1-53" "18625_PS-B1-65"    
 [4] "180712_PS-B1-3-46" "180712_PS-B1-3-48" "18625_PS-B1-63"    
 [7] "18625_PS-B1-52" "18625_PS-B1-24" "18625_PS-B1-66"    
[10] "18625_PS-B1-56" "180712_PS-B1-3-90" "180712_PS-B1-3-83" 
[13] "18625_PS-B1-58" "18625_PS-B1-69" "18625_PS-B1-94"    
[16] "18625_PS-B1-49" "180712_PS-B1-3-103" "180712_PS-B1-3-20" 
[19] "18625_PS-B1-43" "18625_PS-B1-91" "18625_PS-B1-27"    
[22] "18625_PS-B1-7" "18625_PS-B1-73" "18625_PS-B1-31"    
[25] "180712_PS-B1-3-101" "18625_PS-B1-99" "18625_PS-B1-96"    
[28] "18625_PS-B1-119" "18625_PS-B1-130" "18625_PS-B1-98"    
[31] "18625_PS-B1-134" "18625_PS-B1-133" "18625_PS-B1-18"    
[34] "18625_PS-B1-23" "18625_PS-B1-16" "18625_PS-B1-62"    
[37] "18625_PS-B1-109" "18625_PS-B1-117" "18625_PS-B1-60"    
[40] "18625_PS-B1-136"   
The names in the RUN table of the osw files do not match the mzML file names.
Check if the file names are correct.
Error in getRunNames(dataPath, oswMerged, params) : 
Name mismatch between osw and mzML files."

Where is the error? 

Many greetings

**Comment by shubham1637** [comment]
Hi,
  You shouldn't change `metabo` folder in the package. This is just an example data for test cases.
Instead you should have the folder hierarchy. Create `osw` and `xics` folders and have them at the same level and run the command again. You can also look at the test example to see how the command is run:
https://github.com/shubham1637/DIAlignR/blob/bb2617b2a7deeac8a9c53017cbe103710e9a207c/tests/testthat/test_align_dia_runs.R#L132

**Comment by bruadi** [comment]
Hi,
thanks for your quick reply!
I have now done as you said.
However, I still get the same error message... .
I have now matched the filenames in the osw file with those in my datapath, this is correct. However, the filenames in the osw file is still not matched with the file names in my xics directory.
What else can this be?

Greetings

**Comment by bruadi** [comment]
When I use DrawAlignR, my .chrom.mzML files are recognized....

**Comment by shubham1637** [comment]
Could you try this?
```
params <- paramsDIAlignR()
params[["chromFile"]] <- '.chrom.mzML'
alignTargetedRuns(Other inputs, params = params)
```

**Comment by bruadi** [comment]
It works, thank you!
